function f =luoyiman_localbest(x1,x2,x3,x4,x5,X1,y1,Xt,yt)%求解粒子环形邻域中的局部最优个体
K0=[x1;x2;x3;x4;x5];
K1=[fun(x1,X1,y1,Xt,yt), ...
    fun(x2,X1,y1,Xt,yt), ...
    fun(x3,X1,y1,Xt,yt), ...
    fun(x4,X1,y1,Xt,yt), ...
    fun(x5,X1,y1,Xt,yt)];
[maxvalue index]=min(K1);
plocalbest=K0(index,:);
f=plocalbest;